x// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6KeeeBskfUTQSxsXUwQXEWEjyCsL5F4',
    appId: '1:476996211974:web:d88a84b409115e6621fa87',
    messagingSenderId: '476996211974',
    projectId: 'z1pass',
    authDomain: 'z1pass.firebaseapp.com',
    storageBucket: 'z1pass.appspot.com',
    measurementId: 'G-VQJGFPSB3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4JZ8Zl2I6y1qxBPWtkKf2YCtYuA4QW6c',
    appId: '1:476996211974:android:583b80a2222c39ad21fa87',
    messagingSenderId: '476996211974',
    projectId: 'z1pass',
    storageBucket: 'z1pass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClIajFLiTToWE7nWxXeW1Mos5Cq99qnsY',
    appId: '1:476996211974:ios:1b04d8a3988e738921fa87',
    messagingSenderId: '476996211974',
    projectId: 'z1pass',
    storageBucket: 'z1pass.appspot.com',
    iosBundleId: 'com.example.z1pass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClIajFLiTToWE7nWxXeW1Mos5Cq99qnsY',
    appId: '1:476996211974:ios:13d72accd9e7f9a721fa87',
    messagingSenderId: '476996211974',
    projectId: 'z1pass',
    storageBucket: 'z1pass.appspot.com',
    iosBundleId: 'com.example.z1pass.RunnerTests',
  );
}
